Repository Financial-Times/node-health-check, pull requests merged in 2020-06, with the labels that each got.

#74 Remove the reference for the tcp-ip check so that it does not keep the process running if there is no other work needing to be done
  lib/check/tcp-ip.js
Labels: release:patch

#83 Require node 10 or later
  MIGRATION.md
  README.md
  package.json
Labels: breaking, release:major

#108 swap out request for axios
  lib/check.js
  lib/check/graphite-threshold.js
  lib/check/ping-url.js
  package-lock.json
  package.json
  test/unit/lib/check/graphite-threshold.test.js
  test/unit/lib/check/ping-url.test.js
  test/unit/mock/axios.mock.js
Labels: release:minor

#110 update lodash and make snyk a development dependency
  .snyk
  package-lock.json
  package.json
Labels: release:patch
